/**
 * All MCP tool definitions (schemas) for the GitHub MCP Server.
 * Exported as a flat array and consumed by the ListToolsRequestSchema handler.
 */

export const toolDefinitions = [

  // ── REPOSITORIES ──────────────────────────────────────────────
  { name: "list_repos", description: "List all your GitHub repositories, sorted by most recently updated.", inputSchema: { type: "object", properties: { per_page: { type: "number" }, type: { type: "string", enum: ["all","public","private","forks","sources"] } }, required: [] } },
  { name: "get_repo", description: "Get full details about a specific repository.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" } }, required: ["repo"] } },
  { name: "create_repo", description: "Create a new GitHub repository.", inputSchema: { type: "object", properties: { name: { type: "string" }, description: { type: "string" }, private: { type: "boolean" }, auto_init: { type: "boolean" } }, required: ["name"] } },
  { name: "delete_repo", description: "⚠️ IRREVERSIBLY delete a repository. Always confirms before acting.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, confirmed: { type: "boolean" } }, required: ["repo", "confirmed"] } },
  { name: "search_repos", description: "Search GitHub repositories by keyword or topic.", inputSchema: { type: "object", properties: { query: { type: "string" }, per_page: { type: "number" } }, required: ["query"] } },
  { name: "get_repo_topics", description: "Get the topics/tags applied to a repository.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" } }, required: ["repo"] } },
  { name: "set_repo_topics", description: "Set/replace all topics on a repository.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, topics: { type: "array", items: { type: "string" } } }, required: ["repo", "topics"] } },
  { name: "fork_repo", description: "Fork a repository into your account.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" } }, required: ["owner", "repo"] } },
  { name: "get_repo_traffic", description: "Get view and clone traffic stats for a repository (last 14 days).", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" } }, required: ["repo"] } },
  { name: "update_repo_settings", description: "Update repo description, homepage, visibility, or feature flags.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, description: { type: "string" }, homepage: { type: "string" }, private: { type: "boolean" }, has_issues: { type: "boolean" }, has_wiki: { type: "boolean" }, has_projects: { type: "boolean" } }, required: ["repo"] } },

  // ── BRANCHES ──────────────────────────────────────────────────
  { name: "list_branches", description: "List all branches in a repository.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" } }, required: ["repo"] } },
  { name: "get_branch", description: "Get details about a specific branch.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, branch: { type: "string" } }, required: ["repo", "branch"] } },
  { name: "create_branch", description: "Create a new branch from an existing branch.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, new_branch: { type: "string" }, from_branch: { type: "string" } }, required: ["repo", "new_branch"] } },
  { name: "delete_branch", description: "⚠️ Delete a branch. Confirms before acting.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, branch: { type: "string" }, confirmed: { type: "boolean" } }, required: ["repo", "branch", "confirmed"] } },
  { name: "rename_branch", description: "Rename an existing branch.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, branch: { type: "string" }, new_name: { type: "string" } }, required: ["repo", "branch", "new_name"] } },
  { name: "get_branch_protection", description: "Get protection rules for a branch.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, branch: { type: "string" } }, required: ["repo", "branch"] } },

  // ── COMMITS ───────────────────────────────────────────────────
  { name: "list_commits", description: "List recent commits on a branch with author and message.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, branch: { type: "string" }, per_page: { type: "number" }, since: { type: "string" }, until: { type: "string" }, author: { type: "string" } }, required: ["repo"] } },
  { name: "get_commit_diff", description: "See what files changed in a specific commit.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, commit_sha: { type: "string" } }, required: ["repo", "commit_sha"] } },
  { name: "compare_branches", description: "Compare two branches: ahead/behind count and differing commits.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, base: { type: "string" }, head: { type: "string" } }, required: ["repo", "base", "head"] } },
  { name: "get_commit_history", description: "Full formatted commit history table for a repo/branch.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, branch: { type: "string" }, per_page: { type: "number" } }, required: ["repo"] } },

  // ── FILES & CONTENT ───────────────────────────────────────────
  { name: "get_file_contents", description: "Read the contents of a file in a repository.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, path: { type: "string" }, branch: { type: "string" } }, required: ["repo", "path"] } },
  { name: "list_directory", description: "List files and folders in a repository directory.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, path: { type: "string" }, branch: { type: "string" } }, required: ["repo"] } },
  { name: "create_or_update_file", description: "⚠️ Create or update a file with a commit. Confirms first.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, path: { type: "string" }, content: { type: "string" }, message: { type: "string" }, branch: { type: "string" }, confirmed: { type: "boolean" } }, required: ["repo", "path", "content", "message", "confirmed"] } },
  { name: "delete_file", description: "⚠️ Delete a file from a repository with a commit. Confirms first.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, path: { type: "string" }, message: { type: "string" }, branch: { type: "string" }, confirmed: { type: "boolean" } }, required: ["repo", "path", "message", "confirmed"] } },

  // ── ISSUES ────────────────────────────────────────────────────
  { name: "list_issues", description: "List issues in a repository (filter by state, label).", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, state: { type: "string", enum: ["open","closed","all"] }, label: { type: "string" }, per_page: { type: "number" } }, required: ["repo"] } },
  { name: "get_issue", description: "Get full details of a single issue including comments.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, issue_number: { type: "number" } }, required: ["repo", "issue_number"] } },
  { name: "create_issue", description: "Create a new issue.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, title: { type: "string" }, body: { type: "string" }, labels: { type: "array", items: { type: "string" } }, assignees: { type: "array", items: { type: "string" } }, milestone: { type: "number" } }, required: ["repo", "title"] } },
  { name: "update_issue", description: "Update an issue: title, body, state, labels, milestone.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, issue_number: { type: "number" }, title: { type: "string" }, body: { type: "string" }, state: { type: "string", enum: ["open","closed"] }, labels: { type: "array", items: { type: "string" } }, milestone: { type: "number" } }, required: ["repo", "issue_number"] } },
  { name: "comment_on_issue", description: "Post a comment on an issue or pull request.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, issue_number: { type: "number" }, body: { type: "string" } }, required: ["repo", "issue_number", "body"] } },
  { name: "list_labels", description: "List all labels defined in a repository.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" } }, required: ["repo"] } },
  { name: "create_label", description: "Create a new label with a name and colour.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, name: { type: "string" }, color: { type: "string", description: "Hex colour without #, e.g. ff0000" }, description: { type: "string" } }, required: ["repo", "name", "color"] } },
  { name: "list_milestones", description: "List milestones in a repository.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, state: { type: "string", enum: ["open","closed","all"] } }, required: ["repo"] } },
  { name: "create_milestone", description: "Create a new milestone.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, title: { type: "string" }, description: { type: "string" }, due_on: { type: "string", description: "Due date ISO 8601, e.g. 2025-12-31T00:00:00Z" } }, required: ["repo", "title"] } },

  // ── PULL REQUESTS ─────────────────────────────────────────────
  { name: "list_pull_requests", description: "List pull requests in a repository.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, state: { type: "string", enum: ["open","closed","all"] } }, required: ["repo"] } },
  { name: "get_pull_request", description: "Get full details of a specific pull request.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, pull_number: { type: "number" } }, required: ["repo", "pull_number"] } },
  { name: "create_pull_request", description: "Open a new pull request.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, title: { type: "string" }, head: { type: "string" }, base: { type: "string" }, body: { type: "string" }, draft: { type: "boolean" } }, required: ["repo", "title", "head"] } },
  { name: "merge_pull_request", description: "⚠️ Merge a pull request. Shows full confirmation first.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, pull_number: { type: "number" }, merge_method: { type: "string", enum: ["merge","squash","rebase"] }, commit_title: { type: "string" }, confirmed: { type: "boolean" } }, required: ["repo", "pull_number", "confirmed"] } },
  { name: "get_pr_diff", description: "List files changed in a pull request.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, pull_number: { type: "number" } }, required: ["repo", "pull_number"] } },
  { name: "request_pr_review", description: "Request review from specific GitHub users on a PR.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, pull_number: { type: "number" }, reviewers: { type: "array", items: { type: "string" } } }, required: ["repo", "pull_number", "reviewers"] } },
  { name: "list_pr_reviews", description: "List all reviews on a pull request with their state and body.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, pull_number: { type: "number" } }, required: ["repo", "pull_number"] } },

  // ── RELEASES & TAGS ───────────────────────────────────────────
  { name: "list_releases", description: "List all releases for a repository.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, per_page: { type: "number" } }, required: ["repo"] } },
  { name: "get_latest_release", description: "Get the latest published release for a repository.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" } }, required: ["repo"] } },
  { name: "create_release", description: "Create a new release (and tag).", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, tag_name: { type: "string" }, name: { type: "string" }, body: { type: "string" }, draft: { type: "boolean" }, prerelease: { type: "boolean" }, target_commitish: { type: "string" } }, required: ["repo", "tag_name", "name"] } },
  { name: "list_tags", description: "List all git tags in a repository.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, per_page: { type: "number" } }, required: ["repo"] } },

  // ── GITHUB ACTIONS / WORKFLOWS ────────────────────────────────
  { name: "list_workflows", description: "List all GitHub Actions workflow files in a repository.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" } }, required: ["repo"] } },
  { name: "list_workflow_runs", description: "List recent runs of a workflow (or all workflows) with status and conclusion.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, workflow_id: { type: "string", description: "Workflow filename e.g. ci.yml, or workflow ID number — omit for all workflows" }, branch: { type: "string" }, status: { type: "string", enum: ["queued","in_progress","completed","waiting","requested","pending"] }, per_page: { type: "number" } }, required: ["repo"] } },
  { name: "get_workflow_run", description: "Get full details about a specific workflow run: status, conclusion, timing, jobs.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, run_id: { type: "number" } }, required: ["repo", "run_id"] } },
  { name: "rerun_workflow", description: "Re-trigger a failed workflow run.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, run_id: { type: "number" } }, required: ["repo", "run_id"] } },
  { name: "cancel_workflow_run", description: "⚠️ Cancel a workflow run that is currently in progress.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, run_id: { type: "number" }, confirmed: { type: "boolean" } }, required: ["repo", "run_id", "confirmed"] } },
  { name: "trigger_workflow",   description: "Manually trigger a workflow_dispatch workflow on a branch.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, workflow_id: { type: "string", description: "Workflow filename e.g. deploy.yml" }, ref: { type: "string", description: "Branch or tag to run on (default: main)" }, inputs: { type: "object", description: "Key-value inputs for the workflow" } }, required: ["repo", "workflow_id"] } },

  // ── STATS, ACTIVITY & PROFILE ─────────────────────────────────
  { name: "get_repo_stats", description: "Contributor stats, language breakdown, stars/forks for a repo.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" } }, required: ["repo"] } },
  { name: "get_repo_traffic", description: "View/clone traffic for a repo over the last 14 days.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" } }, required: ["repo"] } },
  { name: "get_my_activity", description: "Your recent GitHub events across all repos.", inputSchema: { type: "object", properties: { per_page: { type: "number" } }, required: [] } },
  { name: "get_my_profile", description: "Your GitHub profile: name, bio, followers, repos, join date.", inputSchema: { type: "object", properties: {}, required: [] } },
  { name: "list_notifications", description: "List your unread GitHub notifications.", inputSchema: { type: "object", properties: { all: { type: "boolean", description: "If true, show all notifications including read ones" }, per_page: { type: "number" } }, required: [] } },
  { name: "star_repo", description: "Star a repository.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" } }, required: ["owner", "repo"] } },
  { name: "unstar_repo", description: "Unstar a repository.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" } }, required: ["owner", "repo"] } },
  { name: "list_starred_repos", description: "List all repositories you have starred.", inputSchema: { type: "object", properties: { per_page: { type: "number" } }, required: [] } },

  // ── SEARCH ────────────────────────────────────────────────────
  { name: "search_code", description: "Search for code across your repositories.", inputSchema: { type: "object", properties: { query: { type: "string" }, repo: { type: "string" }, language: { type: "string" }, per_page: { type: "number" } }, required: ["query"] } },
  { name: "search_issues", description: "Search issues and PRs across GitHub.", inputSchema: { type: "object", properties: { query: { type: "string" }, per_page: { type: "number" } }, required: ["query"] } },
  { name: "search_commits", description: "Search commits across GitHub by message or author.", inputSchema: { type: "object", properties: { query: { type: "string" }, repo: { type: "string" }, per_page: { type: "number" } }, required: ["query"] } },

  // ── ADMIN & COLLABORATORS ─────────────────────────────────────
  { name: "list_collaborators", description: "List all collaborators on a repository with their permission levels.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" } }, required: ["repo"] } },
  { name: "add_collaborator", description: "Add a collaborator to a repository with a specified permission.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, username: { type: "string" }, permission: { type: "string", enum: ["pull","triage","push","maintain","admin"] } }, required: ["repo", "username"] } },
  { name: "remove_collaborator", description: "⚠️ Remove a collaborator from a repository. Confirms first.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" }, username: { type: "string" }, confirmed: { type: "boolean" } }, required: ["repo", "username", "confirmed"] } },
  { name: "list_deploy_keys", description: "List deploy keys configured on a repository.", inputSchema: { type: "object", properties: { owner: { type: "string" }, repo: { type: "string" } }, required: ["repo"] } },

] as const;
